# docker-compose.yml file example
version: "3.9"
services:
  api-tests-container:
    container_name: api-tests
    build:
      context: .
      dockerfile: ./Dockerfile
    image: qa-project
    networks:
      - default
      - api-network
    entrypoint: [ "/wait_for_local_server.sh" ]
    command: pytest -n 8 --env ${APP_ENV_NAME} -m ${TAG}
